# Realtime audio — PipeWire PulseAudio config
# Requires: realtime-privileges package + user in realtime group

context.modules = [
    { name = libpipewire-module-rt
        args = {
            nice.level = -11
            rt.prio    = 98
        }
        flags = [ ifexists nofail ]
    }
]

stream.properties = {
    node.latency = 512/48000
}
