# Convolution EQ — PipeWire filter chain
# Get .wav files from https://autoeq.app (choose "Convolution" format)

context.modules = [
    { name = libpipewire-module-filter-chain
        flags = [ nofail ]
        args = {
            node.description = "Equalizer"
            media.name       = "Equalizer"
            filter.graph = {
                nodes = [
                    { type = builtin
                      label = convolver
                      name  = convolver
                      config = { filename = "<EQ_WAV_PATH>" }
                    }
                ]
                inputs  = [ "convolver:In" ]
                outputs = [ "convolver:Out" ]
            }
            audio.channels = 2
            capture.props = {
                node.name   = "input.effect_convolver"
                media.class = Audio/Sink
            }
            playback.props = {
                node.name   = "output.effect_convolver"
                node.passive = true
            }
        }
    }
]
